/**
 * CSS Generator Tests
 *
 * Tests for generateThemeCSS function that transforms
 * theme configurations into Tailwind v4-compatible CSS.
 */

import { describe, it, expect } from 'vitest';
import { generateThemeCSS } from '../../src/theme/css-generator.js';
import { defaultTheme } from '../../src/theme/defaults.js';

describe('generateThemeCSS', () => {
  describe('output structure', () => {
    it('returns a non-empty string', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(typeof css).toBe('string');
      expect(css.length).toBeGreaterThan(0);
    });

    it('contains :root block', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain(':root');
      expect(css).toMatch(/:root\s*\{/);
    });

    it('contains .dark block', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('.dark');
      expect(css).toMatch(/\.dark\s*\{/);
    });

    it('contains @media (prefers-color-scheme: dark) block', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('@media (prefers-color-scheme: dark)');
      expect(css).toMatch(/@media\s*\(\s*prefers-color-scheme:\s*dark\s*\)/);
    });

    it('contains header comment block', () => {
      const css = generateThemeCSS(defaultTheme);
      // Should have a comment at the start
      expect(css).toMatch(/^\/\*\*/);
      expect(css).toContain('Generated by');
    });
  });

  describe('semantic color variables', () => {
    it('defines --color-primary variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-primary:');
    });

    it('defines --color-primary-foreground variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-primary-foreground:');
    });

    it('defines --color-secondary variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-secondary:');
    });

    it('defines --color-secondary-foreground variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-secondary-foreground:');
    });

    it('defines --color-destructive variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-destructive:');
    });

    it('defines --color-destructive-foreground variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-destructive-foreground:');
    });

    it('defines --color-background variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-background:');
    });

    it('defines --color-foreground variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-foreground:');
    });

    it('defines --color-muted variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-muted:');
    });

    it('defines --color-muted-foreground variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-muted-foreground:');
    });

    it('defines --color-ring variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-ring:');
    });

    it('defines --color-card variable', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--color-card:');
    });

    it('all semantic color variables have oklch values', () => {
      const css = generateThemeCSS(defaultTheme);
      // Extract all --color-* definitions from :root block
      const rootMatch = css.match(/:root\s*\{([\s\S]*?)\n\}/);
      expect(rootMatch).not.toBeNull();
      const rootBlock = rootMatch![1];
      const colorVars = rootBlock.match(/--color-[\w-]+:\s*[^;]+/g) || [];

      // All color vars should have oklch values
      for (const varDef of colorVars) {
        expect(varDef).toMatch(/oklch\(/);
      }
    });
  });

  describe('component variables', () => {
    it('defines button component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-button-radius:');
      expect(css).toContain('--ui-button-primary-bg:');
      expect(css).toContain('--ui-button-primary-text:');
      expect(css).toContain('--ui-button-secondary-bg:');
      expect(css).toContain('--ui-button-destructive-bg:');
      expect(css).toContain('--ui-button-outline-bg:');
      expect(css).toContain('--ui-button-ghost-bg:');
    });

    it('defines dialog component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-dialog-radius:');
      expect(css).toContain('--ui-dialog-bg:');
      expect(css).toContain('--ui-dialog-text:');
    });

    it('defines input component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-input-radius:');
      expect(css).toContain('--ui-input-bg:');
      expect(css).toContain('--ui-input-text:');
      expect(css).toContain('--ui-input-border:');
      expect(css).toContain('--ui-input-border-focus:');
      expect(css).toContain('--ui-input-ring:');
      expect(css).toContain('--ui-input-border-error:');
    });

    it('defines switch component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-switch-track-bg:');
      expect(css).toContain('--ui-switch-track-bg-checked:');
      expect(css).toContain('--ui-switch-ring:');
    });

    it('defines checkbox component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-checkbox-bg-checked:');
      expect(css).toContain('--ui-checkbox-border-checked:');
      expect(css).toContain('--ui-checkbox-ring:');
    });

    it('defines radio component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-radio-border-checked:');
      expect(css).toContain('--ui-radio-dot-color:');
      expect(css).toContain('--ui-radio-ring:');
    });

    it('defines select component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-select-bg:');
      expect(css).toContain('--ui-select-border:');
      expect(css).toContain('--ui-select-border-focus:');
      expect(css).toContain('--ui-select-dropdown-bg:');
      expect(css).toContain('--ui-select-option-check:');
    });

    it('defines tabs component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-tabs-list-bg:');
      expect(css).toContain('--ui-tabs-tab-text:');
      expect(css).toContain('--ui-tabs-tab-active-bg:');
      expect(css).toContain('--ui-tabs-indicator-color:');
    });

    it('defines accordion component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-accordion-border:');
      expect(css).toContain('--ui-accordion-header-text:');
      expect(css).toContain('--ui-accordion-panel-text:');
    });

    it('defines calendar component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-calendar-bg:');
      expect(css).toContain('--ui-calendar-selected-bg:');
      expect(css).toContain('--ui-calendar-today-border:');
    });

    it('defines popover component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-popover-bg:');
      expect(css).toContain('--ui-popover-text:');
      expect(css).toContain('--ui-popover-border:');
    });

    it('defines tooltip component variables', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('--ui-tooltip-bg:');
      expect(css).toContain('--ui-tooltip-text:');
    });
  });

  describe('radius values', () => {
    it('uses correct sm radius values', () => {
      const smConfig = { ...defaultTheme, radius: 'sm' as const };
      const css = generateThemeCSS(smConfig);
      expect(css).toContain('--ui-button-radius: 0.25rem');
      expect(css).toContain('--ui-dialog-radius: 0.375rem');
      expect(css).toContain('--ui-input-radius: 0.25rem');
    });

    it('uses correct md radius values', () => {
      const mdConfig = { ...defaultTheme, radius: 'md' as const };
      const css = generateThemeCSS(mdConfig);
      expect(css).toContain('--ui-button-radius: 0.375rem');
      expect(css).toContain('--ui-dialog-radius: 0.5rem');
      expect(css).toContain('--ui-input-radius: 0.375rem');
    });

    it('uses correct lg radius values', () => {
      const lgConfig = { ...defaultTheme, radius: 'lg' as const };
      const css = generateThemeCSS(lgConfig);
      expect(css).toContain('--ui-button-radius: 0.5rem');
      expect(css).toContain('--ui-dialog-radius: 0.75rem');
      expect(css).toContain('--ui-input-radius: 0.5rem');
    });

    it('radius variables only appear in :root block', () => {
      const css = generateThemeCSS(defaultTheme);
      // Dark mode should not redefine radius (it inherits from :root)
      const darkMatch = css.match(/\.dark\s*\{([\s\S]*?)\n\}/);
      expect(darkMatch).not.toBeNull();
      const darkBlock = darkMatch![1];
      expect(darkBlock).not.toContain('--ui-button-radius:');
      expect(darkBlock).not.toContain('--ui-dialog-radius:');
    });
  });

  describe('dark mode', () => {
    it('.dark block contains color overrides', () => {
      const css = generateThemeCSS(defaultTheme);
      // Extract .dark block
      const darkMatch = css.match(/\.dark\s*\{([\s\S]*?)\n\}/);
      expect(darkMatch).not.toBeNull();
      const darkBlock = darkMatch![1];
      expect(darkBlock).toContain('--color-primary:');
      expect(darkBlock).toContain('--color-background:');
    });

    it('@media block contains :root:not(.light) selector', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain(':root:not(.light)');
    });

    it('dark mode colors are different from light mode', () => {
      const css = generateThemeCSS(defaultTheme);

      // Extract :root block colors
      const rootMatch = css.match(/:root\s*\{([\s\S]*?)\n\}/);
      expect(rootMatch).not.toBeNull();
      const rootBlock = rootMatch![1];

      // Extract .dark block colors
      const darkMatch = css.match(/\.dark\s*\{([\s\S]*?)\n\}/);
      expect(darkMatch).not.toBeNull();
      const darkBlock = darkMatch![1];

      // Primary color should be different
      const rootPrimary = rootBlock.match(/--color-primary:\s*([^;]+)/);
      const darkPrimary = darkBlock.match(/--color-primary:\s*([^;]+)/);

      expect(rootPrimary).not.toBeNull();
      expect(darkPrimary).not.toBeNull();
      expect(rootPrimary![1].trim()).not.toBe(darkPrimary![1].trim());
    });

    it('dark block contains component variable overrides', () => {
      const css = generateThemeCSS(defaultTheme);
      const darkMatch = css.match(/\.dark\s*\{([\s\S]*?)\n\}/);
      expect(darkMatch).not.toBeNull();
      const darkBlock = darkMatch![1];
      expect(darkBlock).toContain('--ui-button-primary-bg:');
      expect(darkBlock).toContain('--ui-input-bg:');
      expect(darkBlock).toContain('--ui-switch-track-bg-checked:');
    });
  });

  describe('comments', () => {
    it('includes section comments', () => {
      const css = generateThemeCSS(defaultTheme);
      // Should have component section comments
      expect(css).toMatch(/\/\*.*Button.*\*\//i);
      expect(css).toMatch(/\/\*.*Dialog.*\*\//i);
      expect(css).toMatch(/\/\*.*Input.*\*\//i);
    });

    it('header includes generation metadata', () => {
      const css = generateThemeCSS(defaultTheme);
      expect(css).toContain('Lit UI');
    });
  });

  describe('CSS validity', () => {
    it('has balanced braces', () => {
      const css = generateThemeCSS(defaultTheme);
      const openBraces = (css.match(/\{/g) || []).length;
      const closeBraces = (css.match(/\}/g) || []).length;
      expect(openBraces).toBe(closeBraces);
    });

    it('has no unclosed comments', () => {
      const css = generateThemeCSS(defaultTheme);
      const openComments = (css.match(/\/\*/g) || []).length;
      const closeComments = (css.match(/\*\//g) || []).length;
      expect(openComments).toBe(closeComments);
    });

    it('all variable definitions end with semicolon', () => {
      const css = generateThemeCSS(defaultTheme);
      // Find all variable definitions (--color-* and --ui-*)
      const varDefs = css.match(/--(?:color|ui)-[\w-]+:\s*[^;]+/g) || [];
      // There should be many variable definitions
      expect(varDefs.length).toBeGreaterThan(30);

      // Check each definition is followed by a semicolon in the original CSS
      for (const varDef of varDefs) {
        const fullPattern = new RegExp(
          varDef.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ';'
        );
        expect(css).toMatch(fullPattern);
      }
    });
  });

  describe('custom config', () => {
    it('uses provided colors instead of defaults', () => {
      const customConfig = {
        ...defaultTheme,
        colors: {
          ...defaultTheme.colors,
          primary: 'oklch(0.70 0.20 150)', // Different primary color
        },
      };
      const css = generateThemeCSS(customConfig);
      // Should contain the custom primary color (or derived value)
      expect(css).toContain('oklch(0.7');
    });

    it('primary color appears in button, checkbox, switch, and other components', () => {
      const customConfig = {
        ...defaultTheme,
        colors: {
          ...defaultTheme.colors,
          primary: 'oklch(0.55 0.22 290)', // Violet primary
        },
      };
      const css = generateThemeCSS(customConfig);
      // Primary should flow through to all components
      expect(css).toContain('--ui-button-primary-bg: oklch(0.55 0.22 290)');
      expect(css).toContain('--ui-checkbox-bg-checked: oklch(0.55 0.22 290)');
      expect(css).toContain('--ui-switch-track-bg-checked: oklch(0.55 0.22 290)');
      expect(css).toContain('--ui-radio-dot-color: oklch(0.55 0.22 290)');
      expect(css).toContain('--ui-tabs-indicator-color: oklch(0.55 0.22 290)');
    });
  });
});
