/**
 * CSS Theme Generator
 *
 * Transforms theme configurations into Tailwind v4-compatible CSS.
 * Generates CSS custom properties (--lui-*) that cascade into Shadow DOM.
 *
 * Output includes:
 * - :root block with light mode variables
 * - .dark block with dark mode overrides
 * - @media (prefers-color-scheme: dark) block for system preference support
 * - Border radius variables based on configured scale
 */

import type { ThemeConfig } from './schema.js';
import { deriveDarkMode, deriveForeground } from './color-scale.js';

/**
 * Border radius values for each scale option.
 * Maps the config radius (sm/md/lg) to actual rem values.
 */
const RADIUS_VALUES: Record<ThemeConfig['radius'], { sm: string; md: string; lg: string }> = {
  sm: {
    sm: '0.125rem',
    md: '0.25rem',
    lg: '0.375rem',
  },
  md: {
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
  },
  lg: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
  },
};

/**
 * Generate Tailwind v4-compatible CSS from a theme configuration.
 *
 * @param config - Complete theme configuration
 * @returns CSS string with :root, .dark, and @media blocks
 */
export function generateThemeCSS(config: ThemeConfig): string {
  const { colors, radius } = config;
  const radiusValues = RADIUS_VALUES[radius];

  // Derive foreground colors for each semantic color
  const primaryForeground = deriveForeground(colors.primary);
  const secondaryForeground = deriveForeground(colors.secondary);
  const destructiveForeground = deriveForeground(colors.destructive);
  const mutedForeground = deriveForeground(colors.muted);

  // Derive dark mode variants
  const darkColors = {
    primary: deriveDarkMode(colors.primary),
    secondary: deriveDarkMode(colors.secondary),
    destructive: deriveDarkMode(colors.destructive),
    background: deriveDarkMode(colors.background),
    foreground: deriveDarkMode(colors.foreground),
    muted: deriveDarkMode(colors.muted),
  };

  // Derive dark mode foregrounds
  const darkPrimaryForeground = deriveForeground(darkColors.primary);
  const darkSecondaryForeground = deriveForeground(darkColors.secondary);
  const darkDestructiveForeground = deriveForeground(darkColors.destructive);
  const darkMutedForeground = deriveForeground(darkColors.muted);

  return `/**
 * Lit UI Theme CSS
 * Generated by Lit UI CLI
 *
 * This file contains CSS custom properties for theming.
 * Variables use the --lui-* prefix and cascade into Shadow DOM.
 */

/* ==========================================================================
 * Light Mode (Default)
 * ========================================================================== */
:root {
  /* Semantic Colors */
  --lui-primary: ${colors.primary};
  --lui-primary-foreground: ${primaryForeground};

  --lui-secondary: ${colors.secondary};
  --lui-secondary-foreground: ${secondaryForeground};

  --lui-destructive: ${colors.destructive};
  --lui-destructive-foreground: ${destructiveForeground};

  --lui-background: ${colors.background};
  --lui-foreground: ${colors.foreground};

  --lui-muted: ${colors.muted};
  --lui-muted-foreground: ${mutedForeground};

  /* Border Radius Scale */
  --lui-radius-sm: ${radiusValues.sm};
  --lui-radius-md: ${radiusValues.md};
  --lui-radius-lg: ${radiusValues.lg};
}

/* ==========================================================================
 * Dark Mode (Class-based)
 * Applied when .dark class is present on an ancestor element.
 * ========================================================================== */
.dark {
  --lui-primary: ${darkColors.primary};
  --lui-primary-foreground: ${darkPrimaryForeground};

  --lui-secondary: ${darkColors.secondary};
  --lui-secondary-foreground: ${darkSecondaryForeground};

  --lui-destructive: ${darkColors.destructive};
  --lui-destructive-foreground: ${darkDestructiveForeground};

  --lui-background: ${darkColors.background};
  --lui-foreground: ${darkColors.foreground};

  --lui-muted: ${darkColors.muted};
  --lui-muted-foreground: ${darkMutedForeground};
}

/* ==========================================================================
 * Dark Mode (System Preference)
 * Applied when user's system prefers dark mode and .light class is not present.
 * ========================================================================== */
@media (prefers-color-scheme: dark) {
  :root:not(.light) {
    --lui-primary: ${darkColors.primary};
    --lui-primary-foreground: ${darkPrimaryForeground};

    --lui-secondary: ${darkColors.secondary};
    --lui-secondary-foreground: ${darkSecondaryForeground};

    --lui-destructive: ${darkColors.destructive};
    --lui-destructive-foreground: ${darkDestructiveForeground};

    --lui-background: ${darkColors.background};
    --lui-foreground: ${darkColors.foreground};

    --lui-muted: ${darkColors.muted};
    --lui-muted-foreground: ${darkMutedForeground};
  }
}
`;
}
