/**
 * CSS Theme Generator
 *
 * Transforms theme configurations into Tailwind v4-compatible CSS.
 * Generates CSS custom properties (--lui-*) that cascade into Shadow DOM.
 *
 * Output includes:
 * - :root block with light mode variables
 * - .dark block with dark mode overrides
 * - @media (prefers-color-scheme: dark) block for system preference support
 * - Border radius variables based on configured scale
 */

import type { ThemeConfig } from './schema.js';
import { deriveDarkMode, deriveForeground } from './color-scale.js';

/**
 * Border radius values for each scale option.
 * Maps the config radius (sm/md/lg) to actual rem values.
 */
const RADIUS_VALUES: Record<ThemeConfig['radius'], { sm: string; md: string; lg: string }> = {
  sm: {
    sm: '0.125rem',
    md: '0.25rem',
    lg: '0.375rem',
  },
  md: {
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
  },
  lg: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
  },
};

/**
 * Generate Tailwind v4-compatible CSS from a theme configuration.
 *
 * @param config - Complete theme configuration
 * @returns CSS string with :root, .dark, and @media blocks
 */
export function generateThemeCSS(config: ThemeConfig): string {
  const { colors, radius } = config;
  const radiusValues = RADIUS_VALUES[radius];

  // Derive foreground colors for each semantic color
  const primaryForeground = deriveForeground(colors.primary);
  const secondaryForeground = deriveForeground(colors.secondary);
  const destructiveForeground = deriveForeground(colors.destructive);
  const mutedForeground = deriveForeground(colors.muted);

  // Derive dark mode variants
  const darkColors = {
    primary: deriveDarkMode(colors.primary),
    secondary: deriveDarkMode(colors.secondary),
    destructive: deriveDarkMode(colors.destructive),
    background: deriveDarkMode(colors.background),
    foreground: deriveDarkMode(colors.foreground),
    muted: deriveDarkMode(colors.muted),
  };

  // Derive dark mode foregrounds
  const darkPrimaryForeground = deriveForeground(darkColors.primary);
  const darkSecondaryForeground = deriveForeground(darkColors.secondary);
  const darkDestructiveForeground = deriveForeground(darkColors.destructive);
  const darkMutedForeground = deriveForeground(darkColors.muted);

  return `/**
 * Lit UI Theme CSS
 * Generated by Lit UI CLI
 *
 * This file contains CSS custom properties for theming.
 * Component-level variables (--ui-button-*, --ui-dialog-*) are set directly
 * to ensure they cascade properly into Shadow DOM.
 */

/* ==========================================================================
 * Light Mode (Default)
 * ========================================================================== */
:root {
  /* Auto-contrast threshold for button text color calculation */
  --ui-contrast-threshold: 0.7;

  /* Semantic Colors */
  --color-primary: ${colors.primary};
  --color-primary-foreground: ${primaryForeground};
  --color-secondary: ${colors.secondary};
  --color-secondary-foreground: ${secondaryForeground};
  --color-destructive: ${colors.destructive};
  --color-destructive-foreground: ${destructiveForeground};
  --color-background: ${colors.background};
  --color-foreground: ${colors.foreground};
  --color-muted: ${colors.muted};
  --color-muted-foreground: ${mutedForeground};
  --color-accent: ${colors.muted};
  --color-accent-foreground: ${colors.foreground};
  --color-border: ${colors.muted};

  /* Button Component Variables */
  --ui-button-radius: ${radiusValues.md};
  --ui-button-primary-bg: ${colors.primary};
  --ui-button-primary-text: ${primaryForeground};
  --ui-button-secondary-bg: ${colors.secondary};
  --ui-button-secondary-text: ${secondaryForeground};
  --ui-button-secondary-hover-bg: ${colors.muted};
  --ui-button-destructive-bg: ${colors.destructive};
  --ui-button-destructive-text: ${destructiveForeground};
  --ui-button-outline-bg: transparent;
  --ui-button-outline-text: ${colors.foreground};
  --ui-button-outline-border: ${colors.muted};
  --ui-button-outline-hover-bg: ${colors.muted};
  --ui-button-ghost-bg: transparent;
  --ui-button-ghost-text: ${colors.foreground};
  --ui-button-ghost-hover-bg: ${colors.muted};

  /* Dialog Component Variables */
  --ui-dialog-radius: ${radiusValues.lg};
  --ui-dialog-bg: ${colors.background};
  --ui-dialog-text: ${colors.foreground};
}

/* ==========================================================================
 * Dark Mode (Class-based)
 * Applied when .dark class is present on an ancestor element.
 * ========================================================================== */
.dark {
  /* Semantic Colors */
  --color-primary: ${darkColors.primary};
  --color-primary-foreground: ${darkPrimaryForeground};
  --color-secondary: ${darkColors.secondary};
  --color-secondary-foreground: ${darkSecondaryForeground};
  --color-destructive: ${darkColors.destructive};
  --color-destructive-foreground: ${darkDestructiveForeground};
  --color-background: ${darkColors.background};
  --color-foreground: ${darkColors.foreground};
  --color-muted: ${darkColors.muted};
  --color-muted-foreground: ${darkMutedForeground};
  --color-accent: ${darkColors.muted};
  --color-accent-foreground: ${darkColors.foreground};
  --color-border: ${darkColors.muted};

  /* Button Component Variables */
  --ui-button-primary-bg: ${darkColors.primary};
  --ui-button-primary-text: ${darkPrimaryForeground};
  --ui-button-secondary-bg: ${darkColors.secondary};
  --ui-button-secondary-text: ${darkSecondaryForeground};
  --ui-button-secondary-hover-bg: ${darkColors.muted};
  --ui-button-destructive-bg: ${darkColors.destructive};
  --ui-button-destructive-text: ${darkDestructiveForeground};
  --ui-button-outline-text: ${darkColors.foreground};
  --ui-button-outline-border: ${darkColors.muted};
  --ui-button-outline-hover-bg: ${darkColors.muted};
  --ui-button-ghost-text: ${darkColors.foreground};
  --ui-button-ghost-hover-bg: ${darkColors.muted};

  /* Dialog Component Variables */
  --ui-dialog-bg: ${darkColors.background};
  --ui-dialog-text: ${darkColors.foreground};
}

/* ==========================================================================
 * Dark Mode (System Preference)
 * Applied when user's system prefers dark mode and .light class is not present.
 * ========================================================================== */
@media (prefers-color-scheme: dark) {
  :root:not(.light) {
    /* Semantic Colors */
    --color-primary: ${darkColors.primary};
    --color-primary-foreground: ${darkPrimaryForeground};
    --color-secondary: ${darkColors.secondary};
    --color-secondary-foreground: ${darkSecondaryForeground};
    --color-destructive: ${darkColors.destructive};
    --color-destructive-foreground: ${darkDestructiveForeground};
    --color-background: ${darkColors.background};
    --color-foreground: ${darkColors.foreground};
    --color-muted: ${darkColors.muted};
    --color-muted-foreground: ${darkMutedForeground};
    --color-accent: ${darkColors.muted};
    --color-accent-foreground: ${darkColors.foreground};
    --color-border: ${darkColors.muted};

    /* Button Component Variables */
    --ui-button-primary-bg: ${darkColors.primary};
    --ui-button-primary-text: ${darkPrimaryForeground};
    --ui-button-secondary-bg: ${darkColors.secondary};
    --ui-button-secondary-text: ${darkSecondaryForeground};
    --ui-button-secondary-hover-bg: ${darkColors.muted};
    --ui-button-destructive-bg: ${darkColors.destructive};
    --ui-button-destructive-text: ${darkDestructiveForeground};
    --ui-button-outline-text: ${darkColors.foreground};
    --ui-button-outline-border: ${darkColors.muted};
    --ui-button-outline-hover-bg: ${darkColors.muted};
    --ui-button-ghost-text: ${darkColors.foreground};
    --ui-button-ghost-hover-bg: ${darkColors.muted};

    /* Dialog Component Variables */
    --ui-dialog-bg: ${darkColors.background};
    --ui-dialog-text: ${darkColors.foreground};
  }
}
`;
}
