import { resolve, dirname, relative } from 'pathe';
import fsExtra from 'fs-extra';
import { detectCssEntry } from './detect-css-entry.js';
import { success, warn, info, file } from './logger.js';

const { readFile, writeFile } = fsExtra;

/**
 * Theme CSS filename generated by the CLI.
 */
const THEME_FILE = 'lit-ui-theme.css';

/**
 * Find the insertion point for a new import statement.
 * Inserts after any existing @charset or @import lines.
 *
 * @returns The index where the new import should be inserted
 */
function findImportInsertionPoint(lines: string[]): number {
  let insertIndex = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Skip empty lines at the start
    if (!line && insertIndex === 0) {
      continue;
    }

    // Keep going past @charset and @import statements
    if (line.startsWith('@charset') || line.startsWith('@import')) {
      insertIndex = i + 1;
    } else if (line) {
      // Stop at first non-import, non-empty line
      break;
    }
  }

  return insertIndex;
}

/**
 * Inject the lit-ui-theme.css import into the project's CSS entry file.
 *
 * This function:
 * 1. Detects the main CSS entry file (Tailwind entry)
 * 2. Checks if the import already exists (idempotent)
 * 3. Calculates the correct relative path
 * 4. Inserts the import after any existing @charset/@import lines
 *
 * @param cwd - The project root directory
 *
 * @example
 * ```ts
 * await injectThemeImport(process.cwd());
 * // Adds: @import './lit-ui-theme.css'; to src/app/globals.css
 * ```
 */
export async function injectThemeImport(cwd: string): Promise<void> {
  const cssEntry = await detectCssEntry(cwd);

  if (!cssEntry) {
    warn('Could not detect main CSS file.');
    info(`Manually add to your CSS: @import '${THEME_FILE}';`);
    return;
  }

  const cssPath = resolve(cwd, cssEntry);
  const themePath = resolve(cwd, THEME_FILE);

  // Read current content
  const content = await readFile(cssPath, 'utf-8');

  // Check idempotency - already has import
  if (content.includes(THEME_FILE)) {
    info(`Theme import already exists in ${file(cssEntry)}`);
    return;
  }

  // Calculate relative path from CSS file location to theme file
  const cssDir = dirname(cssPath);
  let relativePath = relative(cssDir, themePath);

  // Ensure path starts with ./ for relative imports
  if (!relativePath.startsWith('.') && !relativePath.startsWith('/')) {
    relativePath = `./${relativePath}`;
  }

  // Build import statement
  const importStatement = `@import '${relativePath}';`;

  // Split into lines and find insertion point
  const lines = content.split('\n');
  const insertIndex = findImportInsertionPoint(lines);

  // Insert the import
  lines.splice(insertIndex, 0, importStatement);

  // Write back
  const newContent = lines.join('\n');
  await writeFile(cssPath, newContent, 'utf-8');

  success(`Added theme import to ${file(cssEntry)}`);
}
